add category model
nikitaabo/spring_boot_project pull request #10
Opened 2024-09-17 13:22 UTC by nikitaabo

2024-09-18 13:34 UTC, Elena-Bruyako requested changes
see comments

2024-09-18 13:34 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/controller/CategoryController.java
> +    public List<CategoryResponseDto> getAll() {
```suggestion
    public List<CategoryResponseDto> getAll(@ParameterObject @PageableDefault Pageable pageable) {
```

2024-09-18 13:34 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/controller/CategoryController.java
> +    public CategoryResponseDto getCategoryById(@PathVariable Long id) {
```suggestion
    public CategoryResponseDto getCategoryById(@PathVariable @Positive Long id) {
```

2024-09-18 13:34 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/controller/CategoryController.java
> +    public void deleteCategory(@PathVariable Long id) {
```suggestion
    public void deleteCategory(@PathVariable @Positive Long id) {
```

2024-09-18 13:34 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/controller/CategoryController.java
> +    public List<BookDto> getBooksByCategoryId(@PathVariable Long id) {
```suggestion
    public List<BookDto> getBooksByCategoryId(@PathVariable @Positive Long id) {
```

2024-09-18 13:34 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/models/Book.java
> +    @ManyToMany()
```suggestion
    @ManyToMany
```

2024-09-18 13:34 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/models/Category.java
> +    @Column(nullable = false)
you can add unique also

2024-09-18 13:34 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/models/Category.java
> +    public Category() {
use Lombok annotation instead

2024-09-18 13:34 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/services/CategoryServiceImpl.java
> +                () -> new NoSuchElementException("Couldn't find category with id: " + id)
```suggestion
                () -> new EntityNotFoundException("Couldn't find category with id: " + id)
```

2024-09-19 07:04 UTC, liliia-ponomarenko approved these changes
Awesome 😎

2024-09-19 07:04 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/07-create-categories-table.yaml
> +                    nullable: false
add one empty line at the end of the file (check other files) ;)

2024-09-19 12:07 UTC, merged