add user entity and authentication controller
nikitaabo/spring_boot_project pull request #7
Opened 2024-09-09 18:30 UTC by nikitaabo

2024-09-10 06:54 UTC, Elena-Bruyako requested changes
see comments

2024-09-10 06:54 UTC, Elena-Bruyako commented on pom.xml
> +			<groupId>commons-beanutils</groupId>
remove

2024-09-10 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/controller/AuthenticationController.java
> +
```suggestion
```

2024-09-10 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(errorResponse, HttpStatus.BAD_REQUEST);
```suggestion
        return new ResponseEntity<>(errorResponse, HttpStatus.CONFLICT);
```

2024-09-10 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/exception/ErrorResponse.java
> +    // Геттеры и сеттеры
you can use Lombok annotations, for constructor also

2024-09-10 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/models/User.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, unique = true)
```

2024-09-10 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/services/UserServiceImpl.java
> +        Optional<User> userFromDb = userRepository.findByEmail(registrationRequestDto.getEmail());
```suggestion
        if (userRepository.existsByEmail(registrationRequestDto.email())) {
```

2024-09-10 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/services/UserServiceImpl.java
> +        return userMapper.toDto(userRepository.save(userMapper.toModel(registrationRequestDto)));
bad practice to call methods inline
```suggestion
        User user = userMapper.toModel(registrationRequestDto);
        return userMapper.toDto(userRepository.save(user));
```

2024-09-10 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/validation/FieldMatchValidator.java
> +        }
```suggestion
        Object field = new BeanWrapperImpl(value).getPropertyValue(this.firstField);
        Object fieldMatch = new BeanWrapperImpl(value).getPropertyValue(this.secondField);
        return Objects.equals(field, fieldMatch);
```

2024-09-10 06:54 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                    nullable: false
add unique contraint

2024-09-11 07:52 UTC, okuzan requested changes

2024-09-11 07:52 UTC, okuzan commented on src/main/java/com/example/spring/config/MapperConfig.java
> +//        implementationName = "BookMapperImpl"
remove comment

2024-09-11 07:52 UTC, okuzan commented on src/main/java/com/example/spring/exception/ErrorResponse.java
> +}
make this a record, or use @Data

2024-09-11 07:52 UTC, okuzan commented on src/main/java/com/example/spring/models/User.java
> +@SQLRestriction(value = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE users SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction(value = "is_deleted = FALSE")
```

2024-09-11 12:52 UTC, Elena-Bruyako requested changes
one comment

2024-09-11 12:52 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/exception/ErrorResponse.java
> +    public ErrorResponse(String error, String message) {
remove
`@Data` provides constructor

2024-09-11 13:41 UTC, Elena-Bruyako approved these changes

2024-09-13 14:14 UTC, merged